In [1]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('ai_test.csv', sep='\t', names=['author_name','affliations','article_title','doi'])

In [3]:
df.head()

,author_name,affliations,article_title,doi
0,"author_name,affliations,article_title,doi,volu...",NaN,NaN,NaN
1,"Martin Josef Geiger,""University of the Federal...",NaN,NaN,NaN
2,"Lucas Kletzander,Null,Solving the Torpedo Sche...",NaN,NaN,NaN
3,"Nysret Musliu,""Priv. Dozent and Senior Scienti...",NaN,NaN,NaN
4,"Mohammad Mahdi Amirian,""Department of Electric...",NaN,NaN,NaN

In [13]:
article_titles = pd.read_csv('rate.csv')

In [20]:
article_titles.head(15)

    userId  articleId  rating   timestamp
0        1         31     2.5  1260759144
1        1       1029     3.0  1260759179
2        1       1061     3.0  1260759182
3        1       1129     2.0  1260759185
4        1       1172     4.0  1260759205
5        1       1263     2.0  1260759151
6        1       1287     2.0  1260759187
7        1       1293     2.0  1260759148
8        1       1339     3.5  1260759125
9        1       1343     2.0  1260759131
10       1       1371     2.5  1260759135
11       1       1405     1.0  1260759203
12       1       1953     4.0  1260759191
13       1       2105     4.0  1260759139
14       1       2150     3.0  1260759194

In [26]:
merge = pd.read_csv('merge.csv')
merge.head(15)

,author_name,affliations,article_title,doi,volume,type,userId
0,Martin Josef Geiger,University of the Federal Armed Forces Hamburg...,Solving the Torpedo Scheduling Problem,10.1613/jair.1.11303,Vol. 66 (2019),article,3.0
1,Lucas Kletzander,Null,Solving the Torpedo Scheduling Problem,10.1613/jair.1.11303,Vol. 66 (2019),article,3.0
2,Nysret Musliu,"Priv. Dozent and Senior Scientist, Vienna Univ...",Solving the Torpedo Scheduling Problem,10.1613/jair.1.11303,Vol. 66 (2019),article,3.0
3,Mohammad Mahdi Amirian,Department of Electrical and Computer Engineer...,Xeggora: Exploiting Immune-to-Evidence Symmetr...,10.1613/jair.1.11322,Vol. 66 (2019),article,3.0
4,Saeed Shiry Ghidary,"Amirkabir University of Technology, Tehran, Iran",Xeggora: Exploiting Immune-to-Evidence Symmetr...,10.1613/jair.1.11322,Vol. 66 (2019),article,3.0
5,Krzysztof Magiera,Null,Recognizing Top-Monotonic Preference Profiles ...,10.1613/jair.1.11331,Vol. 66 (2019),article,3.0
6,Piotr Faliszewski,"AGH University of Science and Technology, Krak...",Recognizing Top-Monotonic Preference Profiles ...,10.1613/jair.1.11331,Vol. 66 (2019),article,3.0
7,Stâ€šphane Airiau,Strategic Sourcing at Airbnb,Rationalisation of Profiles of Abstract Argume...,10.1613/jair.5436,Vol. 60 (2017),article,3.0
8,Elise Bonzon,Paris Descartes University,Rationalisation of Profiles of Abstract Argume...,10.1613/jair.5436,Vol. 60 (2017),article,3.0
9,Ulle Endriss,"Institute for Logic, Language and Computation ...",Rationalisation of Profiles of Abstract Argume...,10.1613/jair.5436,Vol. 60 (2017),article,3.0
10,Nicolas Maudet,"LIP6, Sorbonne Universitâ€š",Rationalisation of Profiles of Abstract Argume...,10.1613/jair.5436,Vol. 60 (2017),article,3.0
11,Julien Rossit,Unknown affiliation,Rationalisation of Profiles of Abstract Argume...,10.1613/jair.5436,Vol. 60 (2017),article,3.0
12,Victor Gutierrez-Basulto,"University of Bremen, Faculty of Mathematics, ...",Probabilistic Description Logics for Subjectiv...,10.1613/jair.5222,Vol. 58 (2017),article,3.0
13,Jean Christoph Jung,"University of Bremen, Institute of Computer Sc...",Probabilistic Description Logics for Subjectiv...,10.1613/jair.5222,Vol. 58 (2017),article,3.0
14,Carsten Lutz,"University of Bremen, Germany",Probabilistic Description Logics for Subjectiv...,10.1613/jair.5222,Vol. 58 (2017),article,3.0

In [29]:
ratings_matrix = ratings.pivot_table(index=['movieId'],columns=['userId'],values='rating').reset_index(drop=True)
ratings_matrix.fillna( 0, inplace = True )
ratings_matrix.head(15)

KeyError: 'userId'